### ISSUE TITLE
Support for long product names

### ISSUE THREAD

**Issue by pratiksan** [lwa-project/lsl#31]
Update the `lsl.misc.ionosphere` module to work with the new "long produce names", e.g., http://acc.igs.org/repro3/Long_Product_Filenames_v1.0.pdf

**Comment by jaycedowell** [comment]
That link might be a little outdated based on what I have seen for files on the FTP server we use.

**Comment by jaycedowell** [comment]
There's a branch for this now:  https://github.com/lwa-project/lsl/tree/long_product_names

**Comment by jaycedowell** [comment]
@pratiksan I'm seeing some errors from this branch, e.g., https://github.com/lwa-project/lsl/actions/runs/4631061291/jobs/8193463961.  Can you take a look at them?
