### ISSUE TITLE
Fix TBN simulations of point sources

### ISSUE THREAD

**Issue by ctaylor-physics** [lwa-project/lsl#38]
Amplitude factor in dp.py is calculated in units of power but not converted to voltage before being applied (Task 1). Also small changes could be added to more naturally calculate the geometric phase delay (Task 2-5). 

### Fix Power -> Voltage
- [ ] Line 263 change to `temp[j,:] += numpy.fft.ifft(numpy.sqrt(factor) * numpy.exp(-2j*numpy.pi*freq*(cblDelay - geoDelay)))` 
### Change Geometric Delay Calculations
- [ ] Line 14 add `from astropy.constants import c as speedOfLight`
- [ ] Line 26 add `speedOfLight = speedOfLight.to('m/s').value`
- [ ] Line 247 add: `xyz = numpy.array([std.stand.x, std.stand.y, std.stand.z]) `
- [ ] Line 249 change to: `geoDelay = numpy.dot(topo, xyz) / speedOfLight * 1e9 # s -> ns`

**Comment by jaycedowell** [comment]
I'm not sure that that change to line 263 is the correct fix to make for power vs. voltage.  If you look at the line above, where `factor` is defined, there is already a `numpy.sqrt()` for the `flux` term.

**Comment by jaycedowell** [comment]
For the change away from "aipy-style" delay calculations is there a performance hit with the new approach?

**Comment by jaycedowell** [comment]
The change to line 262 looks better but not all of those terms should be under the square root.

**Comment by jaycedowell** [comment]
Is there a PR coming for this?

**Comment by ctaylor-physics** [comment]
Yes, sorry trying to play catch up for Users Meeting. Quick proposal would be to use the suggested changes to the geometric delay calculation as it is only a 15ms added computation per frame per source. Then for the amplitude factor we would make the following changes:

Line 262: `factor = numpy.sqrt( antResponse * cblGain * flux / (2*numpy.pi)) * rv_samp`

Line 264 adds: `temp /= numpy.sqrt(freq.size/2) # Requantize output to avoid clipping  `

I found that freq.size/2 as a spot fix better covers the 8bit range that we will be clipped to after temp is output. For the mean time at least.

**Comment by ctaylor-physics** [comment]
I created a Pull Request for the changes we discussed here ( #42 ). Let me know if everything looks okay, particularly the last change. I thought that sqrt(freq.size/2) had better coverage over the 8 bits we have access too, but if we want to be extra extra safe to avoid clipping then sqrt(freq.size) is maybe preferable.

**Comment by jaycedowell** [comment]
It looks like the TBN simulation issues have been resolved with #42 and a few other commits.
