### ISSUE TITLE
Trouble using lsl2 in a python3 venv 

### ISSUE THREAD

**Issue by nsbruce** [lwa-project/lsl#7]
Hi,

First off, it's really exciting having all of the lwa-project code on Github! This is great.

I'm trying to setup a new virtual environment on python3 (I've tried 3.6 and 3.7) for lsl 2.0.0. I've based the install on the LWA's [base dockerfile](https://github.com/lwa-project/docker_stacks/blob/master/base/Dockerfile).

Everything installs without error but when I run any of the scripts like correlateTBN.py, I get the following error.

```python
ValueError: Coordinate frame barycentricmeanecliptic not in allowed values ['altaz', 'barycentrictrueecliptic', 'cirs', 'fk4', 'fk4noeterms', 'fk5', 'galactic', 'galacticlsr', 'galactocentric', 'gcrs', 'geocentrictrueecliptic', 'hcrs', 'heliocentrictrueecliptic', 'icrs', 'itrs', 'lsr', 'precessedgeocentric', 'supergalactic']
```

I'm getting this while trying to run through the [low frequency tutorial](https://lda10g.alliance.unm.edu/tutorial/) All-Sky Imaging section. So straight from the pdf I run `correlateTBN.py -o 120 -s1 -t1 -2 -l 32 056761_000099453` which gives the above error.

It traces back to `from lsl.common import stations` which if run in an iPython shell throws this error as well.

Any advice is appreciated!

**Comment by nsbruce** [comment]
For completeness sake, the output of `python --version` is `3.6.3` and the output of `pip freeze` is below.

```bash
aipy==3.0.1
arff==0.9
asn1crypto==0.24.0
astropy==3.0.5
backcall==0.1.0
backports-abc==0.5
backports.shutil-get-terminal-size==1.0.0
bcrypt==3.1.4
bitstring==3.1.5
bleach==2.1.3
blist==1.3.6
certifi==2018.11.29
cffi==1.11.5
chardet==3.0.4
cryptography==2.4.2
cycler==0.10.0
Cython==0.29.2
deap==1.2.2
decorator==4.3.0
ecdsa==0.13
entrypoints==0.2.3
ephem==3.7.7.0
funcsigs==1.0.2
healpy==1.14.0
html5lib==1.0.1
idna==2.8
importlib-metadata==0.8
ipykernel==4.8.2
ipython==6.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
jedi==0.12.1
Jinja2==2.10
jsonschema==2.6.0
jupyter-client==5.2.4
jupyter-core==4.4.0
kiwisolver==1.0.1
lockfile==0.12.2
lsl==2.0.0
MarkupSafe==1.1.0
matplotlib==3.0.2
mistune==0.8.4
mock==2.0.0
mpmath==1.1.0
nbconvert==5.3.1
nbformat==4.4.0
netaddr==0.7.19
netifaces==0.10.9
nose==1.3.7
notebook==5.7.4
numpy==1.16.0
pandas==0.23.4
pandocfilters==1.4.2
paramiko==2.4.2
parso==0.3.1
path.py==11.5.0
pathlib2==2.3.3
paycheck==1.0.2
pbr==5.1.1
pexpect==4.6.0
pickleshare==0.7.5
prometheus-client==0.3.1
prompt-toolkit==1.0.15
ptyprocess==0.6.0
pyasn1==0.4.3
pycparser==2.18
pyephem==3.7.7.0
Pygments==2.3.1
PyNaCl==1.2.1
pyparsing==2.3.1
python-dateutil==2.7.5
pytz==2018.9
pyzmq==17.1.2
readline==6.2.4.1
requests==2.21.0
scipy==1.2.0
Send2Trash==1.5.0
simplegeneric==0.8.1
singledispatch==3.4.0.3
six==1.12.0
sympy==1.3
terminado==0.8.1
testpath==0.3.1
tornado==5.1.1
traitlets==4.3.2
urllib3==1.24.1
virtualenv==15.1.0
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.4.2
zipp==0.3.3
```

**Comment by jaycedowell** [comment]
I ran into something similar to this a few days ago.  In my case it was a problem the latest version of healpy (that was being installed as a dependency of aipy) needing astropy>=4.0.  I had been holding LSL back to astropy<4 because of some problems with FITS-IDI support but 4.0.1.post1 seems to be ok.

**Comment by nsbruce** [comment]
You're right, `pip install astropy==4.0.1.post1` got rid of that error. Thanks @jaycedowell !
